name: coach-assistant
chat_modes:
  - name: Coach Assistant
    file: .github/chatmodes/coach_assistant.chatmode.md
    instructions: .github/chatmodes/coach_assistant.instructions.md
    commands:
      - /analyze-match [matchday]
      - /scout-player [joueur]
      - /analyze-training [date]
      - /plan-session
      - /review-performance [période]
      - /help-coach
      - /validate-report [chemin]
      - /archive-match [matchday]
